### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by nop33**
Fix typos found in the documentation

### CODE REVIEW

**Comment by drakkan** [comment]
Thank you for reading and fixing all the docs! Very appreciated, english is not my native language as you can see reading the docs

**Comment by nop33** [comment]
No problem my friend, glad I could help!

**Comment by nop33** [comment]
I see that your project does not participate in this year's [Hacktoberfest](https://hacktoberfest.digitalocean.com/). Why not? :)

If you are not planning on adding the `hacktoberfest` topic on your project, would you mind adding the `hacktoberfest-accepted` label to this MR? Thanks and have a nice day!

**Comment by drakkan** [comment]
done!

**Pull request merged**
