### PR TITLE
increase uid:gid limits

### PR DESCRIPTION
**Pull request by mike-unitskyi**

### CODE REVIEW

**Comment by drakkan** [comment]
Hi,

on my system the max allowed value is 4294967294, can you please update the [web UI](https://github.com/drakkan/sftpgo/blob/main/templates/user.html#L267) and the [OpenAPI definition](https://github.com/drakkan/sftpgo/blob/main/httpd/schema/openapi.yaml#L1741) too? Thank you

**Comment by drakkan** [comment]
values bigger than 2147483647 will cause issue with Postgres/MySQL since uid/gid are defined as int and they could also cause issues on 32bit system (I have no way to test this case) since for os.Chown Go expects an integer and not a uint32.

**Comment by mike-unitskyi** [comment]
hi,
2147483647 will be also fine
let me update PR

**Comment by drakkan** [comment]
I'll add a small test case myself after the merge, thank you

**Comment by mike-unitskyi** [comment]
thank you!

**Comment by mike-unitskyi** [comment]
when can i expect for a new release/do you have some specific release cycle?

**Comment by mike-unitskyi** [comment]
nevermind, found that [docker images](https://hub.docker.com/r/drakkan/sftpgo/tags?page=1&ordering=last_updated) are uploaded on each commit to master branch.
Thanks again for your help!

**Comment by drakkan** [comment]
2.0.3 will be released soon, this weekend if I'll find enough free time. 

However git main has some new features it depends on your use case.

**Comment by drakkan** [comment]
Hello,

thank you again for this contribution. We have recently updated our contribution policy and we now require signing a CLA. Agreeing to the CLA clarifies your rights as a contributor and at the same time protects SFTPGo and its users.

More details [here](https://sftpgo.com/cla.html)

You can use the following URL to sign the CLA

https://cla-assistant.io/drakkan/sftpgo?pullRequest=362

Thank you!

**Comment by drakkan** [comment]
Hello @mike-unitskyi 

thank you again for this contribution. We have recently updated our contribution policy and we now require signing a CLA. Agreeing to the CLA clarifies your rights as a contributor and at the same time protects SFTPGo and its users.

More details [here](https://sftpgo.com/cla.html)

You can use the following URL to sign the CLA

https://cla-assistant.io/drakkan/sftpgo?pullRequest=362

Thank you!

**Pull request merged**
