### PR TITLE
update user.html

### PR DESCRIPTION
**Pull request by ryjogo**
add relative

### CODE REVIEW

**Comment by drakkan** [comment]
Hi, thank you for the pull request but maybe we should find a better term. This is a SFTP/FTP/HTTP path in UNIX format. Windows users could get confused from the `relative` term and write something like `\dir\subdir`. I'm not very good at finding the right terms, can you please suggest some alternatives? Maybe "One SFTP/FTP directory path per line ...", "One virtual directory path per line ..." or "One directory path, as seen by the user, per line .."?

**Comment by ryjogo** [comment]
Ah yes OK. Perhaps:

"One virtual directory path per line as dir::perms, for example /somedir::list,download* 

 is fine.

**Comment by drakkan** [comment]
yes please change this way, thank you

**Comment by drakkan** [comment]
merged, thank you

**Pull request closed without merging**
