### PR TITLE
Add performance optimization summary

### PR DESCRIPTION
**Pull request by HiFiPhile**
A simple summary

### CODE REVIEW

**Comment by drakkan** [comment]
Thanks, I would remove the part about WinSCP, I don't want to blame WinSCP or any other sw in the docs.

I think would be useful if you can describe your test server and report the results against OpenSSH that is the reference implementation (and is written in C and use OpenSSL for crypto and so it is very hard to beat) do you agree?

There are other small notes too, but I can add them myself, for example I don't think that my crypto branch will improve sha performance if avx512 is available (I should add one or two line of code, but I haven't an AVX512 server available for testing )

**Comment by HiFiPhile** [comment]
Hi,
I made some modification.
`I would remove the part about WinSCP`
I've removed the WinSCP part.

`I think would be useful if you can describe your test server and report the results against OpenSSH that is the reference implementation `
I've add a phrase about the comparaison, however since the README is already very dense, I don't think it's a good idea to put too much details.

`I don't think that my crypto branch will improve sha performance if avx512 is available`
So some modifications are needed to let AVX512 enabled ? Me neither I don't have a AVX512 machine...

**Comment by drakkan** [comment]
> Hi,
> I made some modification.
> `I would remove the part about WinSCP`
> I've removed the WinSCP part.
> 
> `I think would be useful if you can describe your test server and report the results against OpenSSH that is the reference implementation `
> I've add a phrase about the comparaison, however since the README is already very dense, I don't think it's a good idea to put too much details.
> 
> `I don't think that my crypto branch will improve sha performance if avx512 is available`
> So some modifications are needed to let AVX512 enabled ? Me neither I don't have a AVX512 machine...

we probably need to add replace `sha256.New`

https://github.com/drakkan/crypto/blob/master/ssh/mac.go#L50

with something like this to my crypto branch for AVX512

```
server := sha256.NewAvx512Server()
sha256.NewAvx512(server)
```

or eventually enable avx512 directly inside sha256-simd if it improve ssh/sftp performance

**Comment by jovandeginste** [comment]
I would suggest creating a separate performance document, and referencing it from the main readme. Maybe add a summary in the readme... The performance document could then contain a lot of information and reproduction code, without detracting from the important parts...

**Comment by drakkan** [comment]
> I would suggest creating a separate performance document, and referencing it from the main readme. Maybe add a summary in the readme... The performance document could then contain a lot of information and reproduction code, without detracting from the important parts...

I agree we could create a `docs` directory and add there a "Performance.md" doc

**Comment by HiFiPhile** [comment]
Yes we could reorganize documents. I feel currently README.md is too dense for the first look.

`My idea is to close the issue #69 and summarize the collected info, the hw used for the tests is important, as explained above an AVX512 capable hw could be slower`

Maybe we could wait the new allocator is more elaborated before closing it ?

**Comment by drakkan** [comment]
> Yes we could reorganize documents. I feel currently README.md is too dense for the first look.
> 

you are right we should have separate sections

> `My idea is to close the issue #69 and summarize the collected info, the hw used for the tests is important, as explained above an AVX512 capable hw could be slower`
> 
> Maybe we could wait the new allocator become more elaborated before closing it ?

My intention was to avoid to a newcomer to read 30+ comments, 

I suspect that the new allocator will require several months before it could be merged upstream, anyway we have no hurry to close that issue :)

**Comment by drakkan** [comment]
I'll try to reorganize the docs the next weend, I'll remove many details from the main README and I'll add separate documents for specific things in a new `docs` directory. The main README will have links to this specific docs. This way the documentation should be less confused. 

So for example the "Performance" paragraph will become a simple link or it will contain a very concise introduction and then it will contain a link to `/docs/Performance.md` for more details.

Maybe something like an index could help too

@jovandeginste @HiFiPhile @others if you have time your help is welcome, thanks!

**Comment by jovandeginste** [comment]
Should we also refer to an example json config instead of including it verbatim in the readme?

**Comment by drakkan** [comment]
> Should we also refer to an example json config instead of including it verbatim in the readme?

yes, so we don't have to copy it each time a new configuration option is added

**Comment by jovandeginste** [comment]
@drakkan I've done some preliminary changes in a branch [here](https://github.com/jovandeginste/sftpgo/tree/docs)

**Comment by drakkan** [comment]
@jovandeginste it looks very promising, thanks! I think we can compact other sections too, for example the configuration section is huge, we can split the configuration options in a separate doc (all the keys in sftpgo.json), a typical user will start with the defaults and then read the docs only if he want to customize something

anyway great job, thanks!

**Comment by jovandeginste** [comment]
@drakkan sure, I just did some easy stuff :-) Since this will take some time and collaboration, I'm not sure how we should best proceed... I could grant write access to my fork of this project to you and others?

**Comment by drakkan** [comment]
> @drakkan sure, I just did some easy stuff :-) Since this will take some time and collaboration, I'm not sure how we should best proceed... I could grant write access to my fork of this project to you and others?

Yes, this is a way or you could simple send a pull request with your partial work, I think I can find some time the next weekend to try to complete what is missing

**Comment by drakkan** [comment]
@HiFiPhile thanks to the hard work of @jovandeginste we now have a much better docs. I really like it!

Regarding this pull request, here is what I would like to see in the new [performance](https://github.com/drakkan/sftpgo/blob/master/docs/performance.md) section:

- a description of your hardware
- a description of the tested configuration:
  1. baseline configuration: current sftpgo git master that include no golang patch and the current pkg/sftp master. This is the configuration used by anyone
  2. performance optimized configuration with a brief description of the used patch
- tested ciphers, this should include `aes128-gcm@openssh.com` and `aes128-ctr` or `aes256-ctr`
- a brief description of the impact of the applied patches in the test results: the golang patch improve aes-ctr, the allocator patch gives general improvement for pkg/sftp, sha256-simd improves mac performance. So `aes128-gcm@openssh.com` is not improved applying the aes-crt and sha256-simd patch, the numbers for this cipher show the performance gain that can be obtained using the allocator patch (this should clarify the things for pkg/sftp maintainers, see the last comment [here](https://github.com/pkg/sftp/issues/334))
- the numbers for the baseline and patched configuration and a comparison with OpenSSH using the same ciphers, optionally the number for haproxy too. SCP numbers could be useful too: they show what we can achieve with the golang ssh stack. SCP is much simpler than SFTP so it is expected that SFTP is a bit slower

Please let me know what do you think about, 

thanks!

**Comment by HiFiPhile** [comment]
Yeah the docs are much better now ;)

I agree with you with the performance section.

 I'll also try to write a step-by-step guide to run SFTPGo as service on Debian, or somebody wants do it 👍

**Comment by drakkan** [comment]
@HiFiPhile I added some basic instructions to run SFTPGo as service, I tested on a CentOS 7 VM, I think they should work on Debian too. 

The only difference with the Arch package that I maintain is the the SQLite database will be installed in /etc/sftpgo instead of /var/lib/sftpgo, I omitted that step to avoid complications for MySQL and PostgreSQL users

**Pull request closed without merging**
