### PR TITLE
Simplify sed commands in Dockerfile(s)

### LINKED ISSUE #740: Simplify sed commands in Dockerfile(s)
Hi Nicola,

As long as you don't need vars substitution, you could simplify the sed commands in your Dockerfiles using an external `'` instead of `"`.

From:

```
# Modify the default configuration file
RUN sed -i "s|\"users_base_dir\": \"\",|\"users_base_dir\": \"/srv/sftpgo/data\",|" /etc/sftpgo/sftpgo.json && \
    sed -i "s|\"backups\"|\"/srv/sftpgo/backups\"|" /etc/sftpgo/sftpgo.json
```

```
# Modify the default configuration file
RUN sed -i "s|\"users_base_dir\": \"\",|\"users_base_dir\": \"/srv/sftpgo/data\",|" sftpgo.json && \
    sed -i "s|\"backups\"|\"/srv/sftpgo/backups\"|" sftpgo.json && \
    sed -i "s|\"sqlite\"|\"bolt\"|" sftpgo.json
```

to:

```
# Modify the default configuration file
RUN sed -i 's|"users_base_dir": "",|"users_base_dir": "/srv/sftpgo/data",|' /etc/sftpgo/sftpgo.json && \
    sed -i 's|"backups"|"/srv/sftpgo/backups"|' /etc/sftpgo/sftpgo.json
```

```
# Modify the default configuration file
RUN sed -i 's|"users_base_dir": "",|"users_base_dir": "/srv/sftpgo/data",|' sftpgo.json && \
    sed -i 's|"backups"|"/srv/sftpgo/backups"|' sftpgo.json && \
    sed -i 's|"sqlite"|"bolt"|' sftpgo.json
```

ciao
Andrea

### PR DESCRIPTION
**Pull request by puntopaz**
Closes #740

### CODE REVIEW

**Comment by puntopaz** [comment]
PS. I compiled successfully all three Dockerfiles

**Comment by drakkan** [comment]
Thanks, please fix the [DCO check](https://github.com/drakkan/sftpgo/pull/743/checks?check_run_id=5336716936)

**Comment by puntopaz** [comment]
Should be ok now

**Comment by drakkan** [comment]
Thanks

**Pull request merged**
