### PR TITLE
Add a version build arg to the Debian Dockerfile.

### PR DESCRIPTION
**Pull request by henriklundahl**
This adds a build arg to the Debian Dockerfile to be able to build latest master, the latest tag or a specific tag.

### CODE REVIEW

**Comment by drakkan** [comment]
Thanks, very appreciated. Are you interested to do the same improvement for the Alpine based Dockerfile?

**Comment by henriklundahl** [comment]
Sure, I'll give it a shot.

By the way, why are the Dockerfiles so different?

**Comment by drakkan** [comment]
> Sure, I'll give it a shot.
> 
thanks!

> By the way, why are the Dockerfiles so different?

I wrote the Debian Dockerfile myself, the Alpine one is a user contribution, so they have a different structure. I never used Alpine myself and I'm not even a big Docker fan so I don't know it very well, I basically verified that it builds and runs and I accepted the contribution. Both Dockerfiles should work fine even if they are a bit different, if you want to suggest improvements they are welcome!

**Comment by drakkan** [comment]
Thanks!

This change allow to build a specific commit too, for example

```
docker build -t="drakkan/sftpgo" --build-arg TAG=c93d8cecfce24dfaed131dcdd69012514719b34b .
```

**Comment by henriklundahl** [comment]
Yes, that's true. Even a branch would work.

Thanks for merging!

**Pull request merged**
