### PR TITLE
Added charset=utf-8 to application/json content type

### PR DESCRIPTION
**Pull request by JonBendtsen**
This change is linked to https://github.com/drakkan/sftpgo/issues/1101 and should partially alleviate the need to change the content type in the files generated by openapi-generator-cli

Signed-off-by: Jon Bendtsen <github@jonb.dk>

### CODE REVIEW

**Comment by JonBendtsen** [comment]
> Please fix the DCO [check](https://github.com/drakkan/sftpgo/pull/1108/checks?check_run_id=10182392361)

I've now tried that

**Comment by drakkan** [comment]
only the latest commit seems correctly signed

**Comment by JonBendtsen** [comment]
> only the latest commit seems correctly signed

seems like I succeeded now

**Comment by drakkan** [comment]
> > only the latest commit seems correctly signed
> 
> seems like I succeeded now

Thanks, I'll merge this PR later today

**Comment by drakkan** [comment]
Thanks!

**Pull request merged**
