### PR TITLE
How to integrate SFTPGo and ClamAV

### PR DESCRIPTION
**Pull request by JonBendtsen**
This document is an example of how to integrate SFTPGo and ClamAV in a single pod such that the Event Manager in SFTPGo could possibly run clamdscan for every uploaded file.

Signed-off-by: Jon Bendtsen <github@jonb.dk>

### CODE REVIEW

**Comment by drakkan** [comment]
Hello,

thanks for this detailed howto, I haven't yet tested it but I think it's definitely useful but also very specific and will only work with local filesystem. I would prefer to have howto like this as links to external sites (see for example the Active Directory integration or the Traefik howto). Do you have a blog/site where you can publish the howto? Please leave me some more time to think about it better, thanks

**Comment by JonBendtsen** [comment]
I do not have a blog, and I do not intend to start one. What if you made a new folder called user_contributions in the howto folder and then it and similar documents could be put there?

**Comment by JonBendtsen** [comment]
as for only working with local filesystem, I mention that that you can use `--stream` in the :How ClamAV container accesses files in SFTPGo container: segment so ClamAV and SFTPGo does not have to share the filesystem.

Or did you mean Storage backends? True, my description is made with Local storage backend in mind. But what if you in the event manager select `Filesystem events` and also select `Execute sync` wouldn't that be capable of scan before the upload is complete? What happens if the script that scans rejects? I would expect that no part of the file is transferred to SFTPGO are also transferred to the other storage backend, but I suppose that it is a question of write-back or write-through, and it seems like I can not specify either when looking in the docs folder for files for non local storage. (maybe there could be a storage_backend.md file? but that would not contain much, only link to the specific storage backend md files.

**Comment by drakkan** [comment]
My main concern is that people start asking for help/clarifications (for example, see your questions, I think encrypted local filesystem won't work either).
I learned the hard way that once I accept a PR, I have to maintain the feature (or the document in this case) forever, even if the original contributor disappears. 
I appreciate your efforts but I don't have motivation to maintain a such doc sorry, this will take time and work, please don't ask me to invest more for free.

**Comment by JonBendtsen** [comment]
I understand your concerns. What if I posted it under Ideas in the discussion part?

**Comment by drakkan** [comment]
> I understand your concerns. What if I posted it under Ideas in the discussion part?

Sounds good, thanks

**Pull request closed without merging**
