### PR TITLE
do not require the config file to contain all default values

### LINKED ISSUE #208: Define defaults using viper.SetDefault
I noticed a slight issue around configuration. Namely: if the config file containing defaults is missing, environment variables are not recognized.

The root cause of this issue is this: https://github.com/spf13/viper/issues/761

Basically, `AutomaticEnv` doesn't work with `Unmarshal` when the keys that env vars are mapped to does not already exist in Viper via some other way. `AutomaticEnv` tries to look for those keys in environment variables when unmarshaling values on a struct.

I recommend using `SetDefault` to set default values (even empty ones), so that the config file does not have to contain all default/empty values for sftpgo to work.

### PR DESCRIPTION
**Pull request by sagikazarmark**
This PR fixes #208 applying the desired solution instead of setting defaults.

I started moving things forward with Viper, but chances are it will take some time until we can find a good enough solution that can land in Viper.

Till then, this workaround resolves the issue. There are probably more ways this could be tested though.

Let me know what you think.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I removed the test because the global nature of config makes it really hard to effectively test this change 😕 

Generally, I don't think global configuration is a good idea.

**Comment by drakkan** [comment]
Thank you,

I have these changes locally and had planned to write test cases later today:

```
diff --git a/config/config.go b/config/config.go
index 35f410d..c0dd4a1 100644
--- a/config/config.go
+++ b/config/config.go
@@ -165,6 +165,7 @@ func init() {
        replacer := strings.NewReplacer(".", "__")
        viper.SetEnvKeyReplacer(replacer)
        viper.SetConfigName(DefaultConfigName)
+       setViperDefaults()
        viper.AutomaticEnv()
        viper.AllowEmptyEnv(true)
 }
@@ -252,10 +253,8 @@ func LoadConfig(configDir, configName string) error {
        viper.AddConfigPath(".")
        viper.SetConfigName(configName)
        if err = viper.ReadInConfig(); err != nil {
-               logger.Warn(logSender, "", "error loading configuration file: %v. Default configuration will be used: %+v",
-                       err, getRedactedGlobalConf())
-               logger.WarnToConsole("error loading configuration file: %v. Default configuration will be used.", err)
-               return err
+               logger.Warn(logSender, "", "error loading configuration file: %v", err)
+               logger.WarnToConsole("error loading configuration file: %v", err)
        }
        err = viper.Unmarshal(&globalConf)
        if err != nil {
@@ -349,3 +348,91 @@ func checkCommonParamsCompatibility() {
                globalConf.Common.ProxyAllowed = globalConf.SFTPD.ProxyAllowed   //nolint:staticcheck
        }
 }
+
+func setViperDefaults() {
+       viper.SetDefault("common.idle_timeout", globalConf.Common.IdleTimeout)
+       viper.SetDefault("common.upload_mode", globalConf.Common.UploadMode)
+       viper.SetDefault("common.actions.execute_on", globalConf.Common.Actions.ExecuteOn)
+       viper.SetDefault("common.actions.hook", globalConf.Common.Actions.Hook)
+       viper.SetDefault("common.setstat_mode", globalConf.Common.SetstatMode)
+       viper.SetDefault("common.proxy_protocol", globalConf.Common.ProxyProtocol)
+       viper.SetDefault("common.proxy_allowed", globalConf.Common.ProxyAllowed)
+       viper.SetDefault("common.post_connect_hook", globalConf.Common.PostConnectHook)
+       viper.SetDefault("sftpd.bind_port", globalConf.SFTPD.BindPort)
+       viper.SetDefault("sftpd.bind_address", globalConf.SFTPD.BindAddress)
+       viper.SetDefault("sftpd.max_auth_tries", globalConf.SFTPD.MaxAuthTries)
+       viper.SetDefault("sftpd.banner", globalConf.SFTPD.Banner)
+       viper.SetDefault("sftpd.host_keys", globalConf.SFTPD.HostKeys)
+       viper.SetDefault("sftpd.kex_algorithms", globalConf.SFTPD.KexAlgorithms)
+       viper.SetDefault("sftpd.ciphers", globalConf.SFTPD.Ciphers)
+       viper.SetDefault("sftpd.macs", globalConf.SFTPD.MACs)
+       viper.SetDefault("sftpd.trusted_user_ca_keys", globalConf.SFTPD.TrustedUserCAKeys)
+       viper.SetDefault("sftpd.login_banner_file", globalConf.SFTPD.LoginBannerFile)
+       viper.SetDefault("sftpd.enabled_ssh_commands", globalConf.SFTPD.EnabledSSHCommands)
+       viper.SetDefault("sftpd.keyboard_interactive_auth_hook", globalConf.SFTPD.KeyboardInteractiveHook)
+       viper.SetDefault("sftpd.password_authentication", globalConf.SFTPD.PasswordAuthentication)
+       viper.SetDefault("ftpd.bind_port", globalConf.FTPD.BindPort)
+       viper.SetDefault("ftpd.bind_address", globalConf.FTPD.BindAddress)
+       viper.SetDefault("ftpd.banner", globalConf.FTPD.Banner)
+       viper.SetDefault("ftpd.banner_file", globalConf.FTPD.BannerFile)
+       viper.SetDefault("ftpd.active_transfers_port_non_20", globalConf.FTPD.ActiveTransfersPortNon20)
+       viper.SetDefault("ftpd.force_passive_ip", globalConf.FTPD.ForcePassiveIP)
+       viper.SetDefault("ftpd.passive_port_range.start", globalConf.FTPD.PassivePortRange.Start)
+       viper.SetDefault("ftpd.passive_port_range.end", globalConf.FTPD.PassivePortRange.End)
+       viper.SetDefault("ftpd.certificate_file", globalConf.FTPD.CertificateFile)
+       viper.SetDefault("ftpd.certificate_key_file", globalConf.FTPD.CertificateKeyFile)
+       viper.SetDefault("ftpd.tls_mode", globalConf.FTPD.TLSMode)
+       viper.SetDefault("webdavd.bind_port", globalConf.WebDAVD.BindPort)
+       viper.SetDefault("webdavd.bind_address", globalConf.WebDAVD.BindAddress)
+       viper.SetDefault("webdavd.certificate_file", globalConf.WebDAVD.CertificateFile)
+       viper.SetDefault("webdavd.certificate_key_file", globalConf.WebDAVD.CertificateKeyFile)
+       viper.SetDefault("webdavd.cors.enabled", globalConf.WebDAVD.Cors.Enabled)
+       viper.SetDefault("webdavd.cors.allowed_origins", globalConf.WebDAVD.Cors.AllowedOrigins)
+       viper.SetDefault("webdavd.cors.allowed_methods", globalConf.WebDAVD.Cors.AllowedMethods)
+       viper.SetDefault("webdavd.cors.allowed_headers", globalConf.WebDAVD.Cors.AllowedHeaders)
+       viper.SetDefault("webdavd.cors.exposed_headers", globalConf.WebDAVD.Cors.ExposedHeaders)
+       viper.SetDefault("webdavd.cors.allow_credentials", globalConf.WebDAVD.Cors.AllowCredentials)
+       viper.SetDefault("webdavd.cors.max_age", globalConf.WebDAVD.Cors.MaxAge)
+       viper.SetDefault("webdavd.cache.enabled", globalConf.WebDAVD.Cache.Enabled)
+       viper.SetDefault("webdavd.cache.expiration_time", globalConf.WebDAVD.Cache.ExpirationTime)
+       viper.SetDefault("webdavd.cache.max_size", globalConf.WebDAVD.Cache.MaxSize)
+       viper.SetDefault("data_provider.driver", globalConf.ProviderConf.Driver)
+       viper.SetDefault("data_provider.name", globalConf.ProviderConf.Name)
+       viper.SetDefault("data_provider.host", globalConf.ProviderConf.Host)
+       viper.SetDefault("data_provider.port", globalConf.ProviderConf.Port)
+       viper.SetDefault("data_provider.username", globalConf.ProviderConf.Username)
+       viper.SetDefault("data_provider.password", globalConf.ProviderConf.Password)
+       viper.SetDefault("data_provider.sslmode", globalConf.ProviderConf.SSLMode)
+       viper.SetDefault("data_provider.connection_string", globalConf.ProviderConf.ConnectionString)
+       viper.SetDefault("data_provider.sql_tables_prefix", globalConf.ProviderConf.SQLTablesPrefix)
+       viper.SetDefault("data_provider.manage_users", globalConf.ProviderConf.ManageUsers)
+       viper.SetDefault("data_provider.track_quota", globalConf.ProviderConf.TrackQuota)
+       viper.SetDefault("data_provider.pool_size", globalConf.ProviderConf.PoolSize)
+       viper.SetDefault("data_provider.users_base_dir", globalConf.ProviderConf.UsersBaseDir)
+       viper.SetDefault("data_provider.actions.execute_on", globalConf.ProviderConf.Actions.ExecuteOn)
+       viper.SetDefault("data_provider.actions.hook", globalConf.ProviderConf.Actions.Hook)
+       viper.SetDefault("data_provider.external_auth_hook", globalConf.ProviderConf.ExternalAuthHook)
+       viper.SetDefault("data_provider.external_auth_scope", globalConf.ProviderConf.ExternalAuthScope)
+       viper.SetDefault("data_provider.credentials_path", globalConf.ProviderConf.CredentialsPath)
+       viper.SetDefault("data_provider.prefer_database_credentials", globalConf.ProviderConf.PreferDatabaseCredentials)
+       viper.SetDefault("data_provider.pre_login_hook", globalConf.ProviderConf.PreLoginHook)
+       viper.SetDefault("data_provider.manage_users", globalConf.ProviderConf.ManageUsers)
+       viper.SetDefault("data_provider.track_quota", globalConf.ProviderConf.TrackQuota)
+       viper.SetDefault("data_provider.pool_size", globalConf.ProviderConf.PoolSize)
+       viper.SetDefault("data_provider.users_base_dir", globalConf.ProviderConf.UsersBaseDir)
+       viper.SetDefault("data_provider.actions.execute_on", globalConf.ProviderConf.Actions.ExecuteOn)
+       viper.SetDefault("data_provider.actions.hook", globalConf.ProviderConf.Actions.Hook)
+       viper.SetDefault("data_provider.external_auth_hook", globalConf.ProviderConf.ExternalAuthHook)
+       viper.SetDefault("data_provider.external_auth_scope", globalConf.ProviderConf.ExternalAuthScope)
+       viper.SetDefault("data_provider.credentials_path", globalConf.ProviderConf.CredentialsPath)
+       viper.SetDefault("data_provider.prefer_database_credentials", globalConf.ProviderConf.PreferDatabaseCredentials)
+       viper.SetDefault("data_provider.pre_login_hook", globalConf.ProviderConf.PreLoginHook)
+       viper.SetDefault("data_provider.post_login_hook", globalConf.ProviderConf.PostLoginHook)
+       viper.SetDefault("data_provider.post_login_scope", globalConf.ProviderConf.PostLoginScope)
+       viper.SetDefault("data_provider.check_password_hook", globalConf.ProviderConf.CheckPasswordHook)
+       viper.SetDefault("data_provider.check_password_scope", globalConf.ProviderConf.CheckPasswordScope)
+       viper.SetDefault("data_provider.password_hashing.argon2_options.memory", globalConf.ProviderConf.PasswordHashing.Argon2Options.Memory)
+       viper.SetDefault("data_provider.password_hashing.argon2_options.iterations", globalConf.ProviderConf.PasswordHashing.Argon2Options.Iterations)
+       viper.SetDefault("data_provider.password_hashing.argon2_options.parallelism", globalConf.ProviderConf.PasswordHashing.Argon2Options.Parallelism)
+       viper.SetDefault("data_provider.update_mode", globalConf.ProviderConf.UpdateMode)
+       viper.SetDefault("httpd.bind_port", globalConf.HTTPDConfig.BindPort)
+       viper.SetDefault("httpd.bind_address", globalConf.HTTPDConfig.BindAddress)
+       viper.SetDefault("httpd.templates_path", globalConf.HTTPDConfig.TemplatesPath)
+       viper.SetDefault("httpd.static_files_path", globalConf.HTTPDConfig.StaticFilesPath)
+       viper.SetDefault("httpd.backups_path", globalConf.HTTPDConfig.BackupsPath)
+       viper.SetDefault("httpd.auth_user_file", globalConf.HTTPDConfig.AuthUserFile)
+       viper.SetDefault("httpd.certificate_file", globalConf.HTTPDConfig.CertificateFile)
+       viper.SetDefault("httpd.certificate_key_file", globalConf.HTTPDConfig.CertificateKeyFile)
+       viper.SetDefault("http.timeout", globalConf.HTTPConfig.Timeout)
+       viper.SetDefault("http.ca_certificates", globalConf.HTTPConfig.CACertificates)
+       viper.SetDefault("http.skip_tls_verify", globalConf.HTTPConfig.SkipTLSVerify)
+}
```

I will evaluate your patch later and if it works well I will prefer it to my manual approach, thanks!

**Comment by sagikazarmark** [comment]
You implemented what I proposed, I implemented what you prefered in the issue I opened 😄 

I usually prefer setting defaults (or call BindEnv), but it's up to you.

**Comment by drakkan** [comment]
> You implemented what I proposed, I implemented what you prefered in the issue I opened 
> 

it is not so terrible after all :)

> I usually prefer setting defaults (or call BindEnv), but it's up to you.

your patch has a minor issue, you have to remove this [return](https://github.com/drakkan/sftpgo/blob/master/config/config.go#L258) otherwise if a config file is missing `bindEnv` will not be called, however I can do this change myself if I'll merge this patch. 

Out of curiosity why do you prefer the setDefault approach, is it a matter of personal preference or are there technical reasons? I'm asking as a viper user a viper maintainer, thanks

**Comment by sagikazarmark** [comment]
> Out of curiosity why do you prefer the setDefault approach, is it a matter of personal preference or are there technical reasons? I'm asking as a viper user a viper maintainer, thanks

Mostly because it's explicit and you immediately see what keys are defined. Even if you don't have tests, it shows the intent of the author.

Also, you often define a bunch keys (eg. to bind flags to config keys, set aliases, etc). It just feels incomplete to me that you define some, but not all.

Ultimately, it's not a big deal, either way works fine, but I burnt myself with implicit magic in too many cases to always prefer explicit solutions.

**Comment by drakkan** [comment]
Fixed setting explicit defaults, thank you

**Comment by sagikazarmark** [comment]
@drakkan do you think you can tag a new release with this (and previous) changes.

**Comment by drakkan** [comment]
Hi, 

if you need a new tag I have no problem to add it but I would like to at least finalize subsystem support (see #204) before tagging 1.2.0,

thank you for your ideas and PR, really appreciated

**Comment by sagikazarmark** [comment]
Sure, let me know if I can help!

**Comment by drakkan** [comment]
> Sure, let me know if I can help!

Thank you!

I don't know if you can help here. I'm waiting for a feedback from the user requesting subsystem support and maybe I have to add some command line flags to allow further customization or improve the docs. Do you plan to use SFTPGo as SFTP subsystem?

**Comment by sagikazarmark** [comment]
> Do you plan to use SFTPGo as SFTP subsystem?

Nope

**Comment by drakkan** [comment]
> Sure, let me know if I can help!

Hi, 

if you want help please give a try to the latest commit. It should improve cloud backends performance but could introduce some bugs too. For S3 and Azure I have a local simulator so I'm sure that performance is better, for GCS I only have a free (slow) account so I don't know if performance really improved :)

Thank you!

**Comment by sagikazarmark** [comment]
I deployed it in a development environment. I was able to upload a 1.4G file in 1 minute 47 seconds.

**Comment by drakkan** [comment]
thank you for test! Sorry I was not clear enough, upload/download performance is unchanged. I improved the stat performance and to do so I refactoring the directory handling too. Before this patch `mkdir` created a blob object with a traling "/", now it recognize dirs by mimetype (inode/directory) or by prefix, so mkdir/rmdir, rename,listdir and stat could break.

This change should mainly improve webdav performance where a lot of `stat` call are requested.

**Comment by sagikazarmark** [comment]
I don't have webdav enabled anywhere, so 🤷 , but I did test mkdir (actually uploaded to a new prefix), so that worked.

**Pull request closed without merging**
