### PR TITLE
Added sha512crypt support

### PR DESCRIPTION
**Pull request by yeonsh**
This adds support to the sha512crypt password encoding scheme when authenticating users.

### CODE REVIEW

**Comment by drakkan** [comment]
Hi, thanks for your contribution.
The patch is "technically" fine, maybe only a test case is missing but i can add it myself after merging.

I'm not sure that using sha512 for storing passwords is a good idea nowaday: sha512 is a fast cryptographic hash function and I think it is not specifically designed for storing passwords.

Please take a look at the following links to better understand what I mean or google for "password hashing algorithms":

https://stackoverflow.com/questions/11624372/best-practice-for-hashing-passwords-sha256-or-sha512
https://security.stackexchange.com/questions/52041/is-using-sha-512-for-storing-passwords-tolerable
https://rietta.com/blog/bcrypt-not-sha-for-passwords/
https://crackstation.net/hashing-security.htm
https://security.blogoverflow.com/2013/09/about-secure-password-hashing/

Can you please better explain your use case? We use argon2id by default (currently the most secure algo for passwords) and we support bcrypt and pbkdf2 (both sha256 and sha512 variant), can you please explain why they are not good for you? Thanks!

**Comment by drakkan** [comment]
This is sha512 crypt and not sha512, I'll reconsider it. Anyway please explain your use case and why you cannot use the supported algos that should be more secure anyway. Thanks

**Comment by jovandeginste** [comment]
The use case I can think of, is migrating existing set-ups where you have the (current) hash but not the actual password.

**Comment by drakkan** [comment]
Yes, this is useful for migrating from system user's accounts

**Comment by drakkan** [comment]
Hello,

thank you again for this contribution. We have recently updated our contribution policy and we now require signing a CLA. Agreeing to the CLA clarifies your rights as a contributor and at the same time protects SFTPGo and its users.

More details [here](https://sftpgo.com/cla.html)

You can use the following URL to sign the CLA

https://cla-assistant.io/drakkan/sftpgo?pullRequest=49

The contributed code has been rewritten but we would still greatly appreciate it if you could sign the CLA.
Thank you!

**Pull request merged**
