### PR TITLE
docs(cn): support translation for Simplified Chinese

### PR DESCRIPTION
**Pull request by HerbertHe**

### CODE REVIEW

**Comment by drakkan** [comment]
Hi,

I appreciate this PR, but I am unable to maintain the translation for Simplified Chinese myself, so it may become out of date when I make changes to the English version

**Comment by HerbertHe** [comment]
I can help for Chinese translation, just need to let me know via at me~

And maybe I would contribute to web interface for i18n support, because some of users don't speak English💪

**Comment by drakkan** [comment]
> I can help for Chinese translation, just need to let me know via at me~
> 

thanks

> And maybe I would contribute to web interface for i18n support, because some of users don't speak Englishmuscle

To support localizations for the webui we need a proper translation system in place. If you just translate the templates a lot of strings will remain in english, it is something I would like to add soon or later

**Comment by HerbertHe** [comment]
@drakkan 
I am a frontend developer and gopher. For i18n support, I suggest using  frontend schema like i18n-next.

**Comment by drakkan** [comment]
> @drakkan I am a frontend developer and gopher. For i18n support, I suggest using frontend schema like i18n-next.

I'm a backend developer, I never used i18n-next, I'll try to study it.

All the validation errors are generated in Go code, for example take a look [here](https://github.com/drakkan/sftpgo/blob/main/dataprovider/dataprovider.go#L1944).

I think we need a system that is able to translate both the text in the Go code and in the templates. I think `golang.org/x/text/language` and `golang.org/x/text/message` should work, but I haven't looked at them in depth yet.

For now the translation is only an idea without a definite schedule, I think it will require a lot of time

**Comment by HerbertHe** [comment]
Right, if the web interface could be refactored as frontend project by using React and RESTFUL API, we can support i18n easier.

But it will spend a lot time to meet the goal😐

**Comment by HerbertHe** [comment]
Or, we can provide a configuration option `lang` and support custom language file formated like `en.json`. Then we can load the language file to map where they should be.

**Comment by HerbertHe** [comment]
But if we only support `lang` option, we can't support multiple languages switching. So, maybe frontend via JavaScript loading is the best solution.

**Comment by HerbertHe** [comment]
Maybe, we can switch languages via params from routes, like `/en/home` and `/zh/home`. Instead, from query, `?lang=zh`.

If the program could not get the specific language, then fallback to default language like English.

But the built-in language packages would cause the project more and more large... But we can meet the goal only by the backend.

**Comment by drakkan** [comment]
I'm not sure yet about the approach. I want to finalize v2.3.0 and then work on #762. After these developments I'll try to find the time to better evaluate the multi-launguage feature

**Pull request merged**
