### PR TITLE
SFTPgo with docker alpine image and init systemD

### PR DESCRIPTION
**Pull request by binou-31**
- Create Dockerfile
  - ability to build one image who can be launch with multi user with `su-exec` in the `entrypoint` script
- Management with systemD script

### CODE REVIEW

**Comment by drakkan** [comment]
Great contribution, thanks! I'll will give a better look tomorrow (my timezone is GMT+2). 

I was working on a debian based Dockerfile so we'll have debian and alpine Dockerfiles soon! 

This is my partial work:

```
# we use a multi stage build to have a separate build and run env
FROM golang:latest as buildenv
LABEL maintainer="nicola.murino@gmail.com"
# we need sqlite3 only to create the empty database
RUN apt-get update; apt-get install -y sqlite3 
RUN go get -u -ldflags "-s -w -X github.com/drakkan/sftpgo/utils.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/utils.date=`date -u +%FT%TZ`" github.com/drakkan/sftpgo
WORKDIR /go/src/github.com/drakkan/sftpgo
RUN sqlite3 sftpgo.db 'CREATE TABLE "users" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "username" varchar(255) NOT NULL UNIQUE, "password" varchar(255) NULL, "public_keys" text NULL, "home_dir" varchar(255) NOT NULL, "uid" integer NOT NULL, "gid" integer NOT NULL, "max_sessions" integer NOT NULL, "quota_size" bigint NOT NULL, "quota_files" integer NOT NULL, "permissions" text NOT NULL, "used_quota_size" bigint NOT NULL, "used_quota_files" integer NOT NULL, "last_quota_update" bigint NOT NULL, "upload_bandwidth" integer NOT NULL, "download_bandwidth" integer NOT NULL);' 

# now define the run environment
FROM debian:latest

ARG BASE_DIR=/app
ARG USERNAME=sftpgo
ARG DATA_REL_DIR=data

# home dir for sftpgo itself
ENV HOME_DIR=${BASE_DIR}/${USERNAME}
# data dir, this is a volume that will hold logs file and user's home dirs
ENV DATA_DIR=${BASE_DIR}/${DATA_REL_DIR}

RUN mkdir -p ${DATA_DIR}
RUN useradd --system --create-home --no-log-init -d ${HOME_DIR} -s /bin/false ${USERNAME}

WORKDIR ${HOME_DIR} 
COPY --from=buildenv /go/bin/sftpgo .
COPY --from=buildenv /go/src/github.com/drakkan/sftpgo/sftpgo.db .
COPY --from=buildenv /go/src/github.com/drakkan/sftpgo/sftpgo.json .
RUN chown -R ${USERNAME}:${USERNAME} .
RUN chown -R ${USERNAME}:${USERNAME} ${DATA_DIR} 

# run as non root user
USER ${USERNAME} 

EXPOSE 2022 8080

VOLUME [ $DATA_DIR ]

# override some default configuration options using env vars
ENV SFTPGO_HTTPD__BIND_ADDRESS=""
ENV SFTPGO_LOG_FILE_PATH=${DATA_DIR}/sftpgo.log

ENTRYPOINT ["./sftpgo", "serve"]
CMD []

```

maybe we should try to share the systemd file. I'll try to complete the debian Dockerfile and to merge this pull request the next weekend, I'm a bit busy with my daily work :(

**Comment by binou-31** [comment]
hi, 
My timezone is GMT+2 too :) 
no problem, take your time ! i do same !  it's already a great job

**Comment by drakkan** [comment]
did you tested if the provided systemd unit has the problems described here?

https://github.com/moby/moby/issues/6791

**Comment by binou-31** [comment]
> did you tested if the provided systemd unit has the problems described here?
> 
> [moby/moby#6791](https://github.com/moby/moby/issues/6791)

I have not tested systemD script. I use them since a moment in my daily job and i didn't notice any bug.

**Pull request closed without merging**
