### PR TITLE
Refactor the logging system

### PR DESCRIPTION
**Pull request by jovandeginste**
* created a "Log" function for type "Connection"
* created a "log" function for type "Provider"
* replace logger calls to Log/log where possible

I also renamed PGSSQL to PGSQL, as this seemed to be a typo

Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>

### CODE REVIEW

**Comment by jovandeginste** [comment]
I'm sorry for the size of this PR ...

**Comment by drakkan** [comment]
thanks, I'll look at this PR in more detail later, as first impression I don't like all this hardcoded strings:

```
provider.log("debug" ...
```

I'll reuse zerolog log level or I'll add some constants for these string, so type errors could not happen

**Comment by jovandeginste** [comment]
@drakkan I changed the strings to consts; probably not what you want in the end, but might make converting easier later.

**Comment by drakkan** [comment]
thanks!

**Comment by drakkan** [comment]
My last commit should not change the generated logs, please let's me know if I'm wrong and thanks for your contribution it is appreciated

**Comment by jovandeginste** [comment]
I was not entirely happy with the way I changed the dataprovider; I think your way is better...

**Comment by jovandeginste** [comment]
(did not test it yet, btw)

**Pull request merged**
