### PR TITLE
s3: don't paginate to find zero-byte-keyed dirs

### LINKED ISSUE #275: S3: stat potentially paginates through thousands of objects to find zero-byte-keyed dirs
For context, I'm using the S3 storage backend pointed at a custom S3-compatible server (Backblaze B2) with the SFTP frontend. The bucket contains millions of files amounting to tens of TBs of data.
Clients connect via SFTP, create a new directory and upload a few files in there.

`Mkdir()` at root level *consistently* times out (`error creating dir: "/testdir" error: RequestCanceled: request context canceled; caused by: context deadline exceeded`), looking for zero-byte-keyed dirs through `Stat()` first:

https://github.com/drakkan/sftpgo/blob/a8a17a223a0bc35941366c8b462fa7ceaff9bfdb/vfs/s3fs.go#L123-L131

it then calls `getStatCompat()`, which ends up paginating through **all** files in the bucket (if the directory doesn't yet exist):

https://github.com/drakkan/sftpgo/blob/a8a17a223a0bc35941366c8b462fa7ceaff9bfdb/vfs/s3fs.go#L139-L142

Looking at the code it seems like `getStatCompat()` is only used for finding the aforementioned zero-byte keyed objects; is there any reason not to simply `HEAD <name>/`, which correctly returns metadata for zero-byte keys?

I've implemented the change to `Stat()` in a local branch and it works fine; if there aren't any edge cases or incompatibilities that `getStatCompat()` already accounts for I'll happily submit it in a PR.

Thanks!

### PR DESCRIPTION
**Pull request by drakkan**
Fixes #275

@trapped can you please try this patch with your S3 compatible backed?  The initial '/' prefix should be automatically removed when SFTPGo create/check a key.

Of course I gave you the attribution for this patch.

I was a bit confused sorry, for GCS and AzBlob backeds we can get the content-type when we list the keys, for S3 this is not possibile so we have to add the `/` suffix when creating directories so this is not compact code that we could remove. I added some comments to clarify this. Thank you for spotting this issue.

I pushed a similar fix for GCS, the main difference is that for GCS we can remove the check in future since we don't create anymore (since 1.2.x) directories with a trailing `/`.

### CODE REVIEW

**Comment by trapped** [comment]
@drakkan just tested, seems to work well!

**Comment by drakkan** [comment]
> @drakkan just tested, seems to work well!

Thank you and sorry for the confusing info. I think we should also disallow files with a trailing `/` I'll test and eventually fix this after the ongoing API refactoring

**Comment by trapped** [comment]
> Thank you and sorry for the confusing info. I think we should also disallow files with a trailing `/` I'll test and eventually fix this after the ongoing API refactoring

Thank you for the amazing work!

**Comment by drakkan** [comment]
if you use SFTPGo at your company please consider a [sponsorship](https://github.com/sponsors/drakkan) :) thank you!

**Pull request merged**
