### PR TITLE
Fixed an issue that could not be found when sharing folders with spaces at the end

### LINKED ISSUE #1431: [Bug]: Sharing a folder with a space at the end of the name prevents sharing links from working properly
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

If you try to share an entire folder, but it ends with a space character, the links created will not work

### Steps to reproduce

1. Create a folder ends with space
2. Create a share
3. Access one of the three links created, none will be functional.

### Expected behavior

Let the links work

### SFTPGo version

lastest

### Data provider

sqlite

### Installation method

Community Docker image

### Configuration

same thing on vanilla

### Relevant log output

_No response_

### What are you using SFTPGo for?

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hackitect1024**
This closes #1431 .

### CODE REVIEW

**Comment by hackitect1024** [comment]
Hi, @drakkan  I fixed the isuue reported in #1431,PTAL, thanks!

**Comment by drakkan** [comment]
This change simply avoids creating a directory with a trailing space via HTTP API/WebClient. It is still possible via SFTP and FTP. While creating a directory with a trailing space via the WebUI is almost certainly an error, it can be intentional via another protocol. We should actually fix the problem instead of just removing features

**Comment by hackitect1024** [comment]
> This change simply avoids creating a directory with a trailing space via HTTP API/WebClient. It is still possible via SFTP and FTP. While creating a directory with a trailing space via the WebUI is almost certainly an error, it can be intentional via another protocol. We should actually fix the problem instead of just removing features此更改只是避免通过 HTTP API/WebClient 创建带有尾随空格的目录。仍然可以通过 SFTP 和 FTP。虽然通过 WebUI 创建带有尾随空格的目录几乎肯定是一个错误，但它可能是通过其他协议故意造成的。我们应该真正解决问题，而不是仅仅删除功能

**Comment by hackitect1024** [comment]
> This change simply avoids creating a directory with a trailing space via HTTP API/WebClient. It is still possible via SFTP and FTP. While creating a directory with a trailing space via the WebUI is almost certainly an error, it can be intentional via another protocol. We should actually fix the problem instead of just removing features

@drakkan Thanks for your reply, you are right. I re-looked at the code, it should fix it in the `Mkdir` implementation, right?

**Comment by drakkan** [comment]
> > This change simply avoids creating a directory with a trailing space via HTTP API/WebClient. It is still possible via SFTP and FTP. While creating a directory with a trailing space via the WebUI is almost certainly an error, it can be intentional via another protocol. We should actually fix the problem instead of just removing features
> 
> @drakkan Thanks for your reply, you are right. I re-looked at the code, it should fix it in the `Mkdir` implementation, right?

mkdir should allow directories with trailing spaces. It's the sharing code that should be fixed to handle them properly

**Comment by drakkan** [comment]
This was already fixed in the 2.5.x branch. I'll push the fix to the development branch as part of a big change in the next few weeks

**Pull request closed without merging**
