### PR TITLE
Dropzone implementation for drag and drop #951

### PR DESCRIPTION
**Pull request by wooneusean**
Used Dropzone.js v6 to upload multiple files by dragging and dropping and browsing

### CODE REVIEW

**Comment by wooneusean** [comment]
https://user-images.githubusercontent.com/20278298/202751009-073ae578-b9e0-499d-926d-3f789b41b3e3.mp4

**Comment by drakkan** [comment]
Thanks, this patch looks much better than #1059. Files are uploaded as soon as dropped but I see that this is configurable in dropzone settings. I'll start a separate testing branch based on it. Thank you!

**Comment by drakkan** [comment]
Thanks for your work, I merged the Filepond [implementation](https://github.com/drakkan/sftpgo/commit/6ebe7691db6157bbcf38315e1dc49aabc3a12e4e), this PR was very useful to compare Filepond and Dropzone.

Both are excellent libraries, Filepond seems to give more flexibility and ease of use for what is needed in SFTPGo.

This feature would not be implemented without your help, thank you!!!

**Comment by wooneusean** [comment]
Glad I could help, me and probably many others use this and feel like drag and drop is such a needed feature.  I am pretty sure you made a lot of people happy with this change.

**Pull request closed without merging**
