### PR TITLE
Add --s3-force-path-style to portable

### PR DESCRIPTION
**Pull request by vdm**
Hi drakkan. I need force-path-style so I can use portable with minio. What do you think? Thanks for sftpgo!

### CODE REVIEW

**Comment by drakkan** [comment]
Hi,

I forgot to add this configuration parameter to the portable version. Thank you for noticing. I think your patch is incomplete. You don't set the parameter and you don't expose it. Please let me know if you want to finish this work otherwise I'll merge this WIP and I'll add the remaining pieces myself. Thank you

**Comment by vdm** [comment]
Hi drakkan. This is the test command I am using:

`$ go run . portable --s3-access-key user1 --s3-access-secret user1234 --s3-bucket bucket1 --s3-endpoint http://127.0.0.1:9000 --s3-force-path-style --s3-region us-east-1 --log-file-path /dev/stdout --log-verbose --fs-provider s3fs &`

If I run this command from the the main branch it fails like this:
```
unknown flag: --s3-force-path-style
Exit status 1
```

Can you say more about why do you think the parameter is not set or exposed correctly? Could it be that my update to the code works somehow but is not clear enough?

Thank you.

**Comment by drakkan** [comment]
sorry my bad, I quickly reviewed your patch from the phone and I missed some pieces. I just tested it and it works fine

**Comment by drakkan** [comment]
Hello,

thank you again for this contribution. We have recently updated our contribution policy and we now require signing a CLA. Agreeing to the CLA clarifies your rights as a contributor and at the same time protects SFTPGo and its users.

More details [here](https://sftpgo.com/cla.html)

You can use the following URL to sign the CLA

https://cla-assistant.io/drakkan/sftpgo?pullRequest=620

Thank you!

**Comment by drakkan** [comment]
Hello @vdm 

thank you again for this contribution. We have recently updated our contribution policy and we now require signing a CLA. Agreeing to the CLA clarifies your rights as a contributor and at the same time protects SFTPGo and its users.

More details [here](https://sftpgo.com/cla.html)

You can use the following URL to sign the CLA

https://cla-assistant.io/drakkan/sftpgo?pullRequest=620

Thank you!

**Pull request merged**
